apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "awx-web-task.fullname" . }}
  labels:
    app: {{ template "awx-web-task.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.deployment.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "awx-web-task.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: awx-web
          image: "{{ .Values.awx_web.image.repository }}:{{ .Values.awx_web.image.tag }}"
          imagePullPolicy: {{ .Values.awx_web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          volumeMounts:
            - mountPath: /etc/tower
              name: awx-application-config
          env:
            - name: DATABASE_USER
              value: {{ .Values.pg_username }}
            - name: DATABASE_NAME
              value: {{ .Values.pg_database }}
            - name: DATABASE_HOST
              value: {{ .Values.pg_hostname }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.pg_password }}
            - name: AWX_ADMIN_USER
              value: {{ .Values.default_admin_user }}
            - name: AWX_ADMIN_PASSWORD
              value: {{ .Values.default_admin_password }}

        - name: awx-task
          image: "{{ .Values.awx_task.image.repository }}:{{ .Values.awx_task.image.tag }}"
          imagePullPolicy: {{ .Values.awx_task.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/tower
              name: awx-application-config

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: awx-application-config
          configMap:
            name: {{ template "awx-web-task.name" . }}
            items:
              - key: awx_settings
                path: settings.py
              - key: secret_key
                path: SECRET_KEY
